In [ ]:
# View vs copy

In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])  # view means modification in original data
b=a[2:5]
b[:]=0
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [3]:
a=np.array([10,20,30,40,50,60,70,80])  # copy() means modifiying in duplicate file
b=a[2:5].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Reshaping the data
# we know that
#  n(row)*n(col)=n(total_element)
# if we have total_elements=12
# 1*12, 12*1
# 2*6,6*2
# 3*4, 4*3
# if we have total_elements=36
# 1*36, 36*1
# 2*18, 18*2
# 4*9, 9*4
# 3*12, 12*3
#  6*6

In [4]:
a=np.random.randint(1,50,12)
a

array([32, 19, 26, 27, 24, 28, 35, 42,  7, 49, 18, 39])

In [5]:
a.shape

(12,)

In [6]:
a.reshape(2,6)

array([[32, 19, 26, 27, 24, 28],
       [35, 42,  7, 49, 18, 39]])

In [7]:
a.reshape(6,2)

array([[32, 19],
       [26, 27],
       [24, 28],
       [35, 42],
       [ 7, 49],
       [18, 39]])

In [8]:
a.reshape(3,4)

array([[32, 19, 26, 27],
       [24, 28, 35, 42],
       [ 7, 49, 18, 39]])

In [9]:
a.reshape(4,3)

array([[32, 19, 26],
       [27, 24, 28],
       [35, 42,  7],
       [49, 18, 39]])

In [10]:
a=np.random.randint(1,100,72)
a

array([93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31, 98, 92, 68, 58, 44,
       57, 80, 41, 17,  2, 23, 24, 36, 26, 81, 69, 98, 56, 23, 87, 54, 79,
        2, 81, 87, 56, 69, 12, 52, 92, 26, 93, 24, 87, 20, 49, 98, 59, 51,
       77, 59, 71, 70, 88, 58, 76, 70, 85, 61, 80, 51, 58, 89,  6, 56, 13,
       58, 75, 29, 52])

In [11]:
a.shape

(72,)

In [12]:
a.reshape(1,72)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31, 98, 92, 68, 58,
        44, 57, 80, 41, 17,  2, 23, 24, 36, 26, 81, 69, 98, 56, 23, 87,
        54, 79,  2, 81, 87, 56, 69, 12, 52, 92, 26, 93, 24, 87, 20, 49,
        98, 59, 51, 77, 59, 71, 70, 88, 58, 76, 70, 85, 61, 80, 51, 58,
        89,  6, 56, 13, 58, 75, 29, 52]])

In [13]:
a.reshape(72,1)

array([[93],
       [66],
       [ 6],
       [42],
       [ 3],
       [39],
       [35],
       [38],
       [54],
       [17],
       [50],
       [31],
       [98],
       [92],
       [68],
       [58],
       [44],
       [57],
       [80],
       [41],
       [17],
       [ 2],
       [23],
       [24],
       [36],
       [26],
       [81],
       [69],
       [98],
       [56],
       [23],
       [87],
       [54],
       [79],
       [ 2],
       [81],
       [87],
       [56],
       [69],
       [12],
       [52],
       [92],
       [26],
       [93],
       [24],
       [87],
       [20],
       [49],
       [98],
       [59],
       [51],
       [77],
       [59],
       [71],
       [70],
       [88],
       [58],
       [76],
       [70],
       [85],
       [61],
       [80],
       [51],
       [58],
       [89],
       [ 6],
       [56],
       [13],
       [58],
       [75],
       [29],
       [52]])

In [15]:
a.reshape(2,36)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31, 98, 92, 68, 58,
        44, 57, 80, 41, 17,  2, 23, 24, 36, 26, 81, 69, 98, 56, 23, 87,
        54, 79,  2, 81],
       [87, 56, 69, 12, 52, 92, 26, 93, 24, 87, 20, 49, 98, 59, 51, 77,
        59, 71, 70, 88, 58, 76, 70, 85, 61, 80, 51, 58, 89,  6, 56, 13,
        58, 75, 29, 52]])

In [16]:
a.reshape(36,2)

array([[93, 66],
       [ 6, 42],
       [ 3, 39],
       [35, 38],
       [54, 17],
       [50, 31],
       [98, 92],
       [68, 58],
       [44, 57],
       [80, 41],
       [17,  2],
       [23, 24],
       [36, 26],
       [81, 69],
       [98, 56],
       [23, 87],
       [54, 79],
       [ 2, 81],
       [87, 56],
       [69, 12],
       [52, 92],
       [26, 93],
       [24, 87],
       [20, 49],
       [98, 59],
       [51, 77],
       [59, 71],
       [70, 88],
       [58, 76],
       [70, 85],
       [61, 80],
       [51, 58],
       [89,  6],
       [56, 13],
       [58, 75],
       [29, 52]])

In [17]:
a.reshape(3,24)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31, 98, 92, 68, 58,
        44, 57, 80, 41, 17,  2, 23, 24],
       [36, 26, 81, 69, 98, 56, 23, 87, 54, 79,  2, 81, 87, 56, 69, 12,
        52, 92, 26, 93, 24, 87, 20, 49],
       [98, 59, 51, 77, 59, 71, 70, 88, 58, 76, 70, 85, 61, 80, 51, 58,
        89,  6, 56, 13, 58, 75, 29, 52]])

In [18]:
a.reshape(24,3)

array([[93, 66,  6],
       [42,  3, 39],
       [35, 38, 54],
       [17, 50, 31],
       [98, 92, 68],
       [58, 44, 57],
       [80, 41, 17],
       [ 2, 23, 24],
       [36, 26, 81],
       [69, 98, 56],
       [23, 87, 54],
       [79,  2, 81],
       [87, 56, 69],
       [12, 52, 92],
       [26, 93, 24],
       [87, 20, 49],
       [98, 59, 51],
       [77, 59, 71],
       [70, 88, 58],
       [76, 70, 85],
       [61, 80, 51],
       [58, 89,  6],
       [56, 13, 58],
       [75, 29, 52]])

In [19]:
a.reshape(4,18)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31, 98, 92, 68, 58,
        44, 57],
       [80, 41, 17,  2, 23, 24, 36, 26, 81, 69, 98, 56, 23, 87, 54, 79,
         2, 81],
       [87, 56, 69, 12, 52, 92, 26, 93, 24, 87, 20, 49, 98, 59, 51, 77,
        59, 71],
       [70, 88, 58, 76, 70, 85, 61, 80, 51, 58, 89,  6, 56, 13, 58, 75,
        29, 52]])

In [20]:
a.reshape(18,4)

array([[93, 66,  6, 42],
       [ 3, 39, 35, 38],
       [54, 17, 50, 31],
       [98, 92, 68, 58],
       [44, 57, 80, 41],
       [17,  2, 23, 24],
       [36, 26, 81, 69],
       [98, 56, 23, 87],
       [54, 79,  2, 81],
       [87, 56, 69, 12],
       [52, 92, 26, 93],
       [24, 87, 20, 49],
       [98, 59, 51, 77],
       [59, 71, 70, 88],
       [58, 76, 70, 85],
       [61, 80, 51, 58],
       [89,  6, 56, 13],
       [58, 75, 29, 52]])

In [21]:
a.reshape(6,12)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54, 17, 50, 31],
       [98, 92, 68, 58, 44, 57, 80, 41, 17,  2, 23, 24],
       [36, 26, 81, 69, 98, 56, 23, 87, 54, 79,  2, 81],
       [87, 56, 69, 12, 52, 92, 26, 93, 24, 87, 20, 49],
       [98, 59, 51, 77, 59, 71, 70, 88, 58, 76, 70, 85],
       [61, 80, 51, 58, 89,  6, 56, 13, 58, 75, 29, 52]])

In [22]:
a.reshape(12,6)

array([[93, 66,  6, 42,  3, 39],
       [35, 38, 54, 17, 50, 31],
       [98, 92, 68, 58, 44, 57],
       [80, 41, 17,  2, 23, 24],
       [36, 26, 81, 69, 98, 56],
       [23, 87, 54, 79,  2, 81],
       [87, 56, 69, 12, 52, 92],
       [26, 93, 24, 87, 20, 49],
       [98, 59, 51, 77, 59, 71],
       [70, 88, 58, 76, 70, 85],
       [61, 80, 51, 58, 89,  6],
       [56, 13, 58, 75, 29, 52]])

In [23]:
a.reshape(8,9)

array([[93, 66,  6, 42,  3, 39, 35, 38, 54],
       [17, 50, 31, 98, 92, 68, 58, 44, 57],
       [80, 41, 17,  2, 23, 24, 36, 26, 81],
       [69, 98, 56, 23, 87, 54, 79,  2, 81],
       [87, 56, 69, 12, 52, 92, 26, 93, 24],
       [87, 20, 49, 98, 59, 51, 77, 59, 71],
       [70, 88, 58, 76, 70, 85, 61, 80, 51],
       [58, 89,  6, 56, 13, 58, 75, 29, 52]])

In [24]:
a.reshape(9,8)

array([[93, 66,  6, 42,  3, 39, 35, 38],
       [54, 17, 50, 31, 98, 92, 68, 58],
       [44, 57, 80, 41, 17,  2, 23, 24],
       [36, 26, 81, 69, 98, 56, 23, 87],
       [54, 79,  2, 81, 87, 56, 69, 12],
       [52, 92, 26, 93, 24, 87, 20, 49],
       [98, 59, 51, 77, 59, 71, 70, 88],
       [58, 76, 70, 85, 61, 80, 51, 58],
       [89,  6, 56, 13, 58, 75, 29, 52]])

In [ ]:
# Conditional selection in numpy

In [59]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [61]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [62]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [63]:
c=a<=10
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [65]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [34]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [35]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [36]:
a+b ## 1+5 =6 , 2+6 = 8 , 3+7=10, 4+8=12

array([[ 6,  8],
       [10, 12]])

In [37]:
a-b

array([[-4, -4],
       [-4, -4]])

In [38]:
a*b # wrong multiplication

array([[ 5, 12],
       [21, 32]])

In [39]:
a.dot(b) # This is multiplication

array([[19, 22],
       [43, 50]])

In [40]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.sum(a)

45

In [42]:
np.sum(a,axis=1) # Row wise total

array([ 6, 15, 24])

In [43]:
np.sum(a,axis=0) # Column wise total

array([12, 15, 18])

In [ ]:
# Unique ---> It will return unique values or eliminate duplicate vlues
# It will return 3 array
#  1> unique value array
#  2> indexing of original value
#  3> Returning frequency of each unique value

In [44]:
a=np.array([1,2,2,2,3,4,3,2,3,3,3,5,4,6])
a

array([1, 2, 2, 2, 3, 4, 3, 2, 3, 3, 3, 5, 4, 6])

In [46]:
np.unique(a , return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  5, 11, 13]),
 array([1, 4, 5, 2, 1, 1]))

In [ ]:
# Linspace() -->  It will create an array in which differnce of each value will be equal


In [48]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# stacking in Numpy-->
# 1> hstack() --> It will combined Multiple arrays into horizontally
# 2> vstack() --> It will combined multiple array into vertically


In [49]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)


In [50]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
a=[[[1,2,3],[4,5,6],[6,7,8]]]
b=np.array(a)
b

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [53]:
b.ndim

3

In [54]:
b[0][0]

array([1, 2, 3])

In [55]:
b[0][1]

array([4, 5, 6])

In [57]:
b[0][2]

array([6, 7, 8])

In [56]:
b[0][2][1]

7