In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])
b=a[2:5]             #view method
b[:]=0
b
a

array([1, 2, 0, 0, 0, 6])

In [ ]:
# Numpy -- open source library and it is use for scientific calculation

# homogenous
# memory less consume
# less time comsume

In [5]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [6]:
a.size

6

In [7]:
a.ndim

1

In [8]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [10]:
a=np.ones(3)
a

array([1., 1., 1.])

In [12]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
a=np.random.randint(1,10,7)
a

array([8, 9, 6, 1, 2, 9, 4])

In [17]:
a=np.random.rand(5)
a

array([0.45505379, 0.52559992, 0.71703874, 0.93432308, 0.88403891])

In [22]:
a=np.random.randn(5)
a

array([-0.13213092,  0.05122905,  0.09545264,  0.21806882,  0.22631875])

In [25]:
np.random.seed(31)
a=np.random.randint(1,4,3)
a

array([3, 1, 3])

In [27]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a.reshape(2,4)
a.reshape(8,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b=np.arange(7,13).reshape(2,3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [38]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [43]:
np.sum(a,axis=1)

array([ 6, 15])

In [44]:
np.sum(b,axis=0)

array([17, 19, 21])

In [46]:
a=np.array([1,2,2,2,3,4,3,2,3,3,3,5,4,6])
np.unique(a,return_index=True,return_counts=True)


(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  5, 11, 13]),
 array([1, 4, 5, 2, 1, 1]))

In [52]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [54]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)

In [55]:
np.hstack([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Pandas an open source library
# Pandas and data frame are mutable


In [57]:
import pandas as pd


In [71]:
a=pd.DataFrame({
    "EMP_ID":[1,2,3,4,5,6],
    "NAME":['SAM',"RAJ",'SACHINE',"VIRAT","ANIKET","AMAN"],
    "DEPARTMENT":["IT","SALES","DEVELOPER","OPERATOR","IT","IT"],
    "HOURS":[5,6,7,8,9,8]
})
a


EMP_ID     NAME DEPARTMENT  HOURS
0       1      SAM         IT      5
1       2      RAJ      SALES      6
2       3  SACHINE  DEVELOPER      7
3       4    VIRAT   OPERATOR      8
4       5   ANIKET         IT      9
5       6     AMAN         IT      8

In [73]:
b=pd.DataFrame({
    "EMP_ID":[1,2,3,4,5,6],
    "AGE":[22,32,25,26,23,22]
})
b

EMP_ID  AGE
0       1   22
1       2   32
2       3   25
3       4   26
4       5   23
5       6   22

In [74]:
df_merged=pd.merge(a,b, on="EMP_ID")
df_merged

EMP_ID     NAME DEPARTMENT  HOURS  AGE
0       1      SAM         IT      5   22
1       2      RAJ      SALES      6   32
2       3  SACHINE  DEVELOPER      7   25
3       4    VIRAT   OPERATOR      8   26
4       5   ANIKET         IT      9   23
5       6     AMAN         IT      8   22

In [89]:
df=pd.read_csv("/content/placement.csv")
df

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [77]:
df.head(3)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [78]:
df.tail(3)

cgpa  resume_score  placed
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [80]:
df.sample(3)

cgpa  resume_score  placed
27  5.51          6.15       0
12  6.09          7.01       0
9   7.69          7.12       1

In [81]:
df.describe()

cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [84]:
df=df.iloc[:4,:3]
df

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [86]:
df=df.loc[1:3,['cgpa','resume_score']]
df

cgpa  resume_score
1  6.17          5.17
2  8.27          8.86
3  6.88          7.27

In [90]:
df.shape

(100, 3)

In [91]:
s=df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [92]:
p=df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [93]:
p=df.empty
p

False

In [94]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [95]:
df.dropna()

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [97]:

a=df.values
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
 

In [100]:
p=df.sort_values(by='resume_score')
p

cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [104]:
o=df.sort_index()
o


cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [106]:
df['cgpa']=df['cgpa'].astype(int)
df

cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [108]:
s=df['cgpa'].add(4)
s

0     12
1     10
2     12
3     10
4     11
      ..
95    10
96    12
97    10
98    12
99    10
Name: cgpa, Length: 100, dtype: int64

In [110]:
c=df.count()
c

cgpa            100
resume_score    100
placed          100
dtype: int64

In [112]:
x=df.max()
x

cgpa            9.00
resume_score    9.06
placed          1.00
dtype: float64

In [113]:
x=df.min()
x

cgpa            5.00
resume_score    4.95
placed          0.00
dtype: float64

In [114]:
d=df.mean()
d

cgpa            6.4700
resume_score    6.9305
placed          0.5000
dtype: float64

In [115]:
v=df.median()
v

cgpa            6.000
resume_score    7.055
placed          0.500
dtype: float64

In [116]:
g=df.filter(items=['cgpa','placed'])
g

cgpa  placed
0      8       1
1      6       0
2      8       1
3      6       1
4      7       1
..   ...     ...
95     6       0
96     8       1
97     6       0
98     8       1
99     6       0

[100 rows x 2 columns]