In [3]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si=SimpleImputer(strategy='mean')

In [ ]:
df['fever']=si.fit_transform(df[['fever']])

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
# Label Encoding   --> mostly use for target column
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['city']=lb.fit_transform(df['city'])
df['cough']=lb.fit_transform(df['cough'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [ ]:
df.head()

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [ ]:
# Ordinal Encoding  -->

In [ ]:
df=pd.read_csv('/content/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')

In [ ]:
df['fever']=si.fit_transform(df[['fever']])

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df = df.drop(columns = ['age','fever','city'] ,axis=1)

In [ ]:
df.head()

gender cough has_covid
0    Male  Mild        No
1    Male  Mild       Yes
2    Male  Mild        No
3  Female  Mild        No
4  Female  Mild        No

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['No','Yes']])

In [ ]:
df_new=oe.fit_transform(df)

In [ ]:
df_new

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [0., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
# Onehot

In [4]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')

In [6]:
df['fever']=si.fit_transform(df[['fever']])

In [7]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [8]:
df.shape

(100, 6)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe=OneHotEncoder(drop='first',sparse_output = False, dtype=np.int32)

In [11]:
df_new = ohe.fit_transform(df)

In [12]:
df_new

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 0, 1]], dtype=int32)

In [14]:
# Get Dummies
x = pd.get_dummies(df, columns=['gender','cough','city','has_covid'],drop_first=True)

In [15]:
x

age  fever  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60  103.0         True         False       False          True   
1    27  100.0         True         False        True         False   
2    42  101.0         True         False        True         False   
3    31   98.0        False         False       False          True   
4    65  101.0        False         False       False         False   
..  ...    ...          ...           ...         ...           ...   
95   12  104.0        False         False       False         False   
96   51  101.0        False          True       False          True   
97   20  101.0        False         False       False         False   
98    5   98.0        False          True       False         False   
99   10   98.0        False          True       False          True   

    city_Mumbai  has_covid_Yes  
0         False          False  
1         False           True  
2         False          False  
3         False          False  
4          True          False  
..          ...            ...  
95        False          False  
96        False           True  
97        False          False  
98         True          False  
99        False           True  

[100 rows x 8 columns]

In [18]:
l=x.astype(int)

In [19]:
l

age  fever  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60    103            1             0           0             1   
1    27    100            1             0           1             0   
2    42    101            1             0           1             0   
3    31     98            0             0           0             1   
4    65    101            0             0           0             0   
..  ...    ...          ...           ...         ...           ...   
95   12    104            0             0           0             0   
96   51    101            0             1           0             1   
97   20    101            0             0           0             0   
98    5     98            0             1           0             0   
99   10     98            0             1           0             1   

    city_Mumbai  has_covid_Yes  
0             0              0  
1             0              1  
2             0              0  
3             0              0  
4             1              0  
..          ...            ...  
95            0              0  
96            0              1  
97            0              0  
98            1              0  
99            0              1  

[100 rows x 8 columns]

In [20]:
l.shape

(100, 8)

In [ ]:
# Column Transform

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
# Mannually Type column Transform

In [ ]:
# Simpleimputer --> fever
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])

In [ ]:
x_train_fever.shape

(80, 1)

In [ ]:
# Ordinal Encoding --> cough
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [ ]:
x_train_cough.shape

(80, 1)

In [ ]:
# Onehot --> gender city

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

In [ ]:
x_train_gender_city.shape

(80, 4)

In [ ]:
x_train_age=x_train.drop(columns=['gender','city','cough','fever']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [ ]:
x_train_age.shape

(80, 1)

In [ ]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

In [ ]:
x_train_transformed.shape

(80, 7)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import ColumnTransformer

In [ ]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(80, 7)

In [ ]:
# Function Transform

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

x = np.array([[1,2],[3,4]])
log_transform = FunctionTransformer(np.log1p)
x_transformed = log_transform.transform(x)
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
# 1> custom feature engineering

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
x=np.array([[1,2],[3,4]])
def holi(x):
  return np.hstack((x, x**2))

column_transformer = FunctionTransformer(holi)

x_transformer=column_transformer.transform(x)
print(x_transformer)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
x = np.array([[1,2],[3,4]])
def my_scaling(x):
  return x/np.max(x)

custom = FunctionTransformer(my_scaling)

x_trans = custom.transform(x)

print(x_trans)



[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
x = np.array([[1,2],[3,np.nan]])
def my_cleaning(x):
  x[np.isnan(x)]=0
  return x

custom = FunctionTransformer(my_cleaning)

x_trans = custom.transform(x)
print(x_trans)

[[1. 2.]
 [3. 0.]]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/placement.csv')
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
x = df.drop(columns=['placed'])
y=df['placed']

In [ ]:
log_transformed = FunctionTransformer(np.log1p)
x_transformed = log_transformed.transform(x)
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [24]:
import pandas as pd
from sklearn.preprocessing import FunctionTransformer

df = pd.read_csv("/content/covid_toy.csv")
int_list=[]
float_list=[]
object_list=[]

def separate(df):
  for col in df.columns:
    if df[col].dtype =='int64':
      int_list.append(col)
    elif df[col].dtype=='float64':
      float_list.append(col)
    else:
      object_list.append(col)
  return (int_list , float_list , object_list)

transformer=FunctionTransformer(separate)

result = transformer.transform(df)

print('Integer',result[0])
print('Float',result[1])
print('Object',result[2])

Integer ['age']
Float ['fever']
Object ['gender', 'cough', 'city', 'has_covid']


In [25]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
for i in object_list:
  df[i]=lb.fit_transform(df[i])
df.head(5)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [26]:
missing_df = df.isnull().sum().reset_index(name='missing')
missing_df

index  missing
0        age        0
1     gender        0
2      fever       10
3      cough        0
4       city        0
5  has_covid        0

In [27]:
missing_col=[]
for i in df.columns:
  missing=df[i].isnull().sum()
  if missing > 0:
    missing_col.append(i)
print(missing_col)

['fever']


In [ ]:
for i in missing_col:
  if i in int_list:
    from sklearn.impute import SimpleImputer
    si = SimpleImputer(strategy='mean')
    df[i]=si.fit_transform(df[[i]])
  elif i in float_list:
    from sklearn.impute import SimpleImputer
    si = SimpleImputer(strategy='mean')
    df[i]=si.fit_transform(df[[i]])
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64